[project]
name = "sentinel-safe-scripts"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "web3>=7.6.0",
    "eth-account>=0.13.0",
    "eth-utils>=5.0.0",
    "requests>=2.32.0",
    "python-dotenv>=1.0.0",
]

[tool.uv]
package = false