[project]
name = "sentinel-safe-scripts"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "eth-account>=0.13.7",
    "eth-utils>=5.3.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "web3>=7.13.0",
]

[tool.uv]
package = false
